# Generated by Django 5.2.13 on 2026-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='ideal_software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='order_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='sales_channels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
