# Generated by Django 5.2.13 on 2026-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waitlistentry_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='ideal_software',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='platform',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='biggest_slowdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='business_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='current_tools',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='desired_automation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='frustrations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='interest_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='lost_money',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='lost_money_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='time_drains',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='two_hours_saved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='worst_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='sales_channels',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='sales_channels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
